import { NextRequest, NextResponse } from "next/server";
import { requireAdminOrSecret } from "@/lib/admin-auth";
import { getServiceRoleClient } from "@/lib/stripe";
import { seedTerritory } from "@/lib/outreach-territories";

export const runtime = "nodejs";

/**
 * POST /api/admin/outreach/territories — add a city to the founder's list.
 *
 * Body: { city, country } (ISO-3166-1 alpha-2). Localized hashtags and search
 * queries are generated by lib/outreach-territories.ts, so adding "Brno, CZ"
 * from the panel needs no hand-written seed. Priority = insertion order; the
 * unique (country, city) index makes re-adding a no-op.
 */
export async function POST(request: NextRequest) {
  const auth = await requireAdminOrSecret(request);
  if (!auth.ok) return auth.response;

  try {
    const body = await request.json().catch(() => null);
    const city = typeof body?.city === "string" ? body.city.trim().slice(0, 120) : "";
    const country =
      typeof body?.country === "string"
        ? body.country.trim().toUpperCase().slice(0, 2)
        : "";
    if (!city || !/^[A-Z]{2}$/.test(country)) {
      return NextResponse.json(
        { error: "city and a 2-letter country code are required" },
        { status: 400 }
      );
    }

    const db = getServiceRoleClient();
    const { count } = await db
      .from("outreach_territories")
      .select("id", { count: "exact", head: true });

    const { data, error } = await db
      .from("outreach_territories")
      .upsert(
        { ...seedTerritory(city, country), priority: (count ?? 0) + 1 },
        { onConflict: "country,city", ignoreDuplicates: true }
      )
      .select()
      .maybeSingle();
    if (error) throw error;

    return NextResponse.json({
      territory: data,
      added: !!data,
      // null data = the (country, city) pair already existed.
    });
  } catch (e) {
    console.error("Add territory failed:", e);
    return NextResponse.json({ error: "add failed" }, { status: 500 });
  }
}
